# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31f103518a3c81a77b016b7c23442e8911a86b5e7b623402050cf6bf5dbfa111aa5d941243cd9f9c1cc0e0aa1c9aa9418763d4718d6caa6e7eb4537f5700f1e

test:
  secret_key_base: bdd25be49fdecbff419dd1090c5f7bfdc0a1f497e9a19cb172316fa0ae606fa6e6dcd3ea9485a5931e8aefdaf66fcc4b918fe09018cbb84d138099db177a7c1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
